[tool.poetry]
name = "malware-analysis"
version = "0.1.0"
description = "environment for static analysis of malware"
authors = ["Aarav Gupta <aaravgupta@gatech.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
networkx = "^3.3"
matplotlib = "^3.9.1.post1"
tqdm = "^4.66.5"
pyvis = "^0.3.2"
pandas = "^2.2.2"
click = "^8.1.7"
setuptools = "^72.1.0"
wheel = "^0.44.0"
setuptools-rust = "^1.10.1"
iced-x86 = "^1.21.0"
scipy = "^1.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"